onboarding = false

[theme]
name = "terminal"
auto_switch = false

[ui]
agent_panel_sort = "spaces"
sidebar_collapsed_mode = "hidden"

[ui.toast]
delivery = "herdr"

[experimental]
pane_history = true

[ui.sound]
enabled = false

[keys]
prefix = "ctrl+s"
toggle_sidebar = "prefix+b"
new_tab = "prefix+t"
close_tab = "prefix+x"
rename_tab = "prefix+,"
split_vertical = "prefix+%"
split_horizontal = "prefix+\""
focus_pane_left = "ctrl+h"
focus_pane_down = "ctrl+j"
focus_pane_up = "ctrl+k"
focus_pane_right = "ctrl+l"
swap_pane_left = "prefix+shift+h"
swap_pane_down = "prefix+shift+j"
swap_pane_up = "prefix+shift+k"
swap_pane_right = "prefix+shift+l"
new_workspace = "prefix+shift+w"
close_workspace = "prefix+shift+d"
rename_workspace = "prefix+shift+t"

# herdr plugin install qq88976321/herdr-copy-search
[[keys.command]]
key = "prefix+["
type = "shell"
command = "herdr plugin pane open --plugin copy-search --entrypoint copy"

[[keys.command]]
key = "prefix+/"
type = "shell"
command = "herdr plugin pane open --plugin copy-search --entrypoint search"

[[keys.command]]
key = "prefix+tab"
type = "shell"
command = "herdr plugin pane open --plugin copy-search --entrypoint extract"

